### ISSUE TITLE
Bug: <title>

### ISSUE THREAD

**Issue by ZsadanyiDaniel** [ConduitIO/conduit-connector-log#43]
### Bug description

Hello, for some reason i download the latest version put it in the connectors folder, but when a go to the UI and want to add a new connector I am not seeing there so i can't.

### Steps to reproduce

1. download 2. put it in the connectros folder 3. run it 4. try to make a new connection with it

### Version

v.0.4.0 windows

**Comment by hariso** [comment]
Hey @ZsadanyiDaniel! Thanks for opening this issue. I can reproduce it myself too. I see that the API is correctly returning all the connector plugins, but the UI isn't displaying those.

However, the team decided some time ago to deprecate the UI completely and remove it in one of the upcoming releases. We haven't seen people using it a lot, and it takes time to maintain it and update it with features. The recommended way to create pipelines in Conduit is through [pipeline configuration files](https://conduit.io/docs/pipeline-configuration-files/getting-started/).
