### ISSUE TITLE
Bug: <Wrong CONDUIT_CONNECTOR_TOKEN>

### ISSUE THREAD

**Issue by ZsadanyiDaniel** [ConduitIO/conduit-connector-log#44]
### Bug description

This is the error MSG:
PS C:\Users\ZsadanyiDani\Desktop\Conduit_0.11.1\connectors> .\conduit-connector-log.exe
error running plugin: failed to get plugin configuration: "CONDUIT_CONNECTOR_TOKEN" is not set. This indicates you are using an old version of Conduit.Please, consider upgrading to at least v0.11.0. https://github.com/ConduitIO/conduit/releases/latest

### Steps to reproduce

1. try run it in the latest conduit

### Version

v.0.4.0 windows

**Comment by hariso** [comment]
Hi @ZsadanyiDaniel!

>  PS C:\Users\ZsadanyiDani\Desktop\Conduit_0.11.1\connectors> .\conduit-connector-log.exe

Why are you running conduit-connector-log.exe yourself?

**Comment by lovromazgon** [comment]
As @hariso already hinted, this binary is not meant to be run directly, it's a connector plugin for [Conduit](https://github.com/ConduitIO/conduit), see [installing connectors](https://conduit.io/docs/connectors/installing).
